### ISSUE TITLE
update url on a network storage / unc path

### ISSUE THREAD

**Issue by soraryu** [Squirrel/Squirrel.Windows#1175]
This had been mentioned before but the issue seems to have been closed without resolution.
Local file system works well, but a properly configured UNC path (if I paste that path into explorer it works) never finds updates. Pretty annoying for local deployment.

**Comment by Logikgate** [comment]
The last issue was resolved with resolution. The UNC path that was being used was incorrect, it needed two slashes at the beginning in order to be valid.  Do you have two slashes and are they properly escaped?

**Comment by paulcbetts** [comment]
Are you ending the path with a slash? Explorer likes to do that but Squirrel probably doesn't

**Comment by nallar** [comment]
This is still a problem.

A path like `\\SERVER-NAME\share-name\folder\Releases` should be fine.

**Comment by paulcbetts** [comment]
@nallar Yep. Are you passing a path to a Folder, or to a RELEASES file - it should be a path to a *Folder*

**Comment by nallar** [comment]
It is a folder called Releases, which contains a file called RELEASES. This matches the structure in https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/2-packaging.md

**Comment by paulcbetts** [comment]
@nallar Sounds like you're doing things right, I'd debug through Squirrel.exe with the --update parameter set to see what's going on

**Comment by Slion** [comment]
Looks like I'm facing that same issue. Mine is looking like:

    file://server/projects/My%20Project/

Tried both with and without trailing slash, none worked.

**Comment by Slion** [comment]
Interestingly while the file URL above does not work the corresponding Windows UNC path works just file:
    \\server\projects\My Project

**Comment by Thieum** [comment]
@soraryu are you still experiencing this issue with the latest version of Squirrel?

**Comment by soraryu** [comment]
Haven't been able to test this and had to move on to other topics, sorry. Would be great if someone else could test.

**Comment by ussha109** [comment]
I am also facing the same issue. My UNC  path looks like 
\\cubert\\TestProject\\Releases\\
and it seems automatic update is not working.

**Comment by Thieum** [comment]
See also #488 #671 #1331 #1406 
@ussha109 as a workaround try to robocopy/sync the remote folder to something local, make the releasify, then resync back to remote.

Considering some third parties dependencies don't play well with the network, it solved this issue for some of us.

**Comment by anaisbetts** [comment]
@ussha109 That is not a UNC path, you're missing a slash. File URLs aren't supported. Use a regular, correctly formatted UNC path
