### ISSUE TITLE
Running two Squirrel installations make both of them not working

### ISSUE THREAD

**Issue by BartoszPiasecki** [Squirrel/Squirrel.Windows#1620]
**Squirrel version(s)**
1.9.1

**Description**
If anyone runs the installer twice an error occurs:
"Installation has failed , there was an error while installing the application. Check the setup log for more information and contact the author"

**Steps to recreate**
1. Run setup.exe
2. Run setup.exe once again, before first one completed

**Actual behavior**
In most cases, both installations break down. Sometimes one succeeds.
Logs says : "process cannot access the file {mostly .nupkg, but sometimes also dlls from installed app} because it is being used by another process" in System.IO.File.InternalDelete 

**Expected behavior**
Second installation should fail, but first one should procced.

**Additional information**
I checked scenario on others apps that are using squirrel, simillar issues

**Comment by yudioll** [comment]
I have the same problem, is it solved?

**Comment by AaronRZH** [comment]
I have the same problem, is it solved?

**Comment by anaisbetts** [comment]
This should be fixed in 2.0

**Comment by deaktomi** [comment]
I can verify that the issue is gone in 2.0 and the installation is always successful, but the error message still appears for one of the 2 installation processes. Is this the planned behavior? This can be very frustrating for the user because he sees that the installation failed, but still, it succeeds

**Comment by RareScrap** [comment]
@anaisbetts Still exists in 2.0.1. The issue should be reopened.

**Comment by caesay** [comment]
Squirrel is riddled with bugs and is no longer being developed. The last release was 5 years ago. You're best off finding an alternative.

**Comment by anaisbetts** [comment]
@caesay I don't do this to Velopack. You need to Stop.

**Comment by caesay** [comment]
@anaisbetts I am afraid I don't know what you are asking me to (not) do. You asked me previously to not name any alternative options (of which there are a few), and I have respected that and stopped naming alternatives. I occasionally point out to people reviving old issues here that this library is unmaintained. Would you like me to stop mentioning that also?

**Comment by anaisbetts** [comment]
@caesay I would like you to no longer comment in this repo in any way. You have made your views clear. Please keep them to yourself.
