### ISSUE TITLE
Generated shortcut is broken when application executable contains space

### ISSUE THREAD

**Issue by maio** [Squirrel/Squirrel.Windows#368]
When I execute `Update.exe --createShortcut "Some App.exe"` it creates shortcut which target looks like `...\Update.exe --processStart Some App.exe`. Such shortcut doesn't work.

When executable contains space it should be wrapped inside quotes (i.e. `...\Update.exe --processStart "Some App.exe"`).

**Comment by pracucci** [comment]
+1

**Comment by paulcbetts** [comment]
This should be fixed, reopen if it's not

**Comment by rmcshane** [comment]
This still happens with the version that's in Electron 0.35.0.  Is this an Electron issue or a Squirrel.Windows issue?

**Comment by paulcbetts** [comment]
Electron doesn't embed Squirrel, the version you've got depends on your app

**Comment by rmcshane** [comment]
Thank you!

**Comment by lzdnku307** [comment]
Same problem! 
Version: 1.4.0!
C:\Users\Administrator\AppData\Local\sstoefl\Update.exe --processStart Smart TOEFL.exe

**Comment by lzdnku307** [comment]
@paulcbetts

**Comment by lzdnku307** [comment]
fixd
[https://github.com/electron/windows-installer/issues/78](url)
Mybe it's electron-winstaller problem.
