### ISSUE TITLE
NuGet.Squirrel and Mono.Cecil missing dependencies in 1.0.0 release - Not properly merged?

### ISSUE THREAD

**Issue by sickboy** [Squirrel/Squirrel.Windows#416]
<img width="253" alt="2015-08-26 15_29_25-windows shell experience host" src="https://cloud.githubusercontent.com/assets/42661/9494624/4ae04f6e-4c07-11e5-89f6-e8346d42d881.png">

I seem to also get missing reference for Mono.Cecil, im guessing these are ILMerged, but shouldn't they be removed as reference then?

~~~
Could not load file or assembly 'NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
~~~

~~~
       at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__116.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Squirrel.UpdateManager.InstallHelperImpl.CreateUninstallerRegistryEntry(String uninstallCmd, String quietSwitch)
       at Squirrel.UpdateManager.InstallHelperImpl.CreateUninstallerRegistryEntry()
       at Squirrel.UpdateManager.CreateUninstallerRegistryEntry()
       at Squirrel.EasyModeMixin.<>c__DisplayClassf.<UpdateApp>b__7()
       at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
~~~

**Comment by sickboy** [comment]
@paulcbetts still the same in 1.0.1, am I missing something?

**Comment by kc0isg** [comment]
I am getting the same issue with Mono.Cecil.
```
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
File name: 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
   at Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass8.<GetPESquirrelAwareVersion>b__7() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 33
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries) in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 170
   at Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable) in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 32
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass5.<GetAllSquirrelAwareApps>b__2(String x) in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 23
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion) in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 20
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__d4.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 498
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__70.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

The error occurs when I call UpdateManager.ApplyReleases() similar to the following
```c#
var manager = new UpdateManager("...");

var updateInfo = await manager.CheckForUpdate();
await manager.DownloadReleases(updateInfo.ReleasesToApply);
var dirPath = await manager.ApplyReleases(updateInfo);
```

**Comment by paulcbetts** [comment]
This is fixed in 1.0.2

**Comment by myquant** [comment]
![qq 20150910103913](https://cloud.githubusercontent.com/assets/7598526/9778792/e366ec56-57a7-11e5-9fe8-b2c1ddb086d8.png)

still not fixed...

**Comment by paulcbetts** [comment]
There are two separate bugs in this issue
